[package]
name = "promptkit"
version = "0.2.0"
edition = "2024"
description = "Handy tools for working with prompts"
license = "Apache-2.0"

[dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
ignore = "0.4"
tiktoken-rs = "0.9"
